permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: 七弦
  email: lcm.hust@gmail.com
  link: http://joshualeung.github.io
  weibo: http://weibo.com/ming1eung
  github: http://github.com/joshualeung

# 站点信息
title: 莲城笔记 
description: 生活随笔、杂记
url: http://joshualeung.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://pic.yupoo.com/24plus/E2O4V5oL/medium.jpg
favicon: http://pic.yupoo.com/24plus/E2O4V5oL/medium.jpg

# google analytics 设置
ga:
  id: UA-43667383-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: joshua-github

# 主题设置，自动激活某个标签
active: 诗词

# 首页除了最新文章外显示分类
cates: 

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
