# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
permalink: /:year/:month/:day/:title.html
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Johnny的博客

description: 学无止境
# gavatar头像及Favicon
gavatar: http://avatar.csdn.net/C/4/D/1_yinzhong39.jpg
favicon: http://avatar.csdn.net/C/4/D/1_yinzhong39.jpg
# favicon: http://pic.yupoo.com/24plus/E2O4V5oL/medium.jpg

author:
  name: JohnnyYin
  bio: JohnnyYin
  github: enjoydream
  weibo: 729271608
  wechat: enjoy_dream
  csdn: yinzhong39
  qq: 729271608
  email: enjoy930429@gmail.com
  email_md5: daf837849a895608386061ebedcd389b

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
